apiVersion: v1
kind: Service
metadata:
  name: {{ include "dropper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dropper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dropper.selectorLabels" . | nindent 4 }}
